### ISSUE TITLE
Edit profile cancel not working 

### ISSUE THREAD

**Issue by Pratikdate** [Pratikdate/ecard#12]
**Describe the bug**
When user go for edit profile photo but he decided not to change photo there is no way. 

**To Reproduce**
1. Go to user profile 
2. Click edit profile photo 
3. There is cross button click move back 

**Expected behavior**
When user go to edit profile photo and decide to not edit then make cross button click to move back if photo not selected.

**Smartphone (please complete the following information):**
 Phone

**Comment by vamsikandula03** [comment]
Could you please asign this task to me . I would like to work on this issue

**Comment by ShashankDeepak** [comment]
Please assign me this task, I would like to contribute to it.
