### ISSUE TITLE
Require google-services.json file to run the project

### ISSUE THREAD

**Issue by ShashankDeepak** [Pratikdate/ecard#2]
An additional file "google-services.json" is required to run the project otherwise it throws the following error 
```
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\FlutterRepo\ecard\android\app\src\debug\google-services.json
  D:\FlutterRepo\ecard\android\app\src\google-services.json
  D:\FlutterRepo\ecard\android\app\google-services.json


Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 4m 49s
```

The google-services.json is a sensitive file that should not be openly available, but it is essentially required to run the project. Using a suitable channel to provide the file would be the best solution. My suggestion would be to take the Discord ID of the contributor and give the file personally to them via Discord DM. 

Also, if you go ahead with my proposed solution, I have here my Discord ID, and I would like to ask you to grant me the file. -> shashank_deepak

**Comment by Pratikdate** [comment]
Join monitor developer discord community 
https://discord.gg/anZbe56p

**Comment by Pratikdate** [comment]
In discord, you must get the google-services.json file
