### ISSUE TITLE
Improving the Readme file

### ISSUE THREAD

**Issue by woodwolfswee** [Pratikdate/ecard#20]
Hey, I saw a few grammatical errors in the readme file. I could help improve it if you assign this to me.

**Comment by AnanyaSinghal23** [comment]
I would like to work on this issue, please assign it to me. Thank you.

**Comment by AgnivaMaiti** [comment]
Hi! I'm a gssoc'24 contributor, please assign this issue to me, I can correct the errors, thank you!

**Comment by Shubham-Zone** [comment]
@Yashshukla11 i would like to contribute to this issue... kindly assign me
