### ISSUE TITLE
Delete .vscode folder

### ISSUE THREAD

**Issue by say-het** [Pratikdate/ecard#24]
**Description**

 - Issue is that ".vscode" folder is not necessary folder.
 - It depends on system so it creates conflicts with user's existing Extensions, as not every user have same extensions.

I would like to work on this issue please assign it to me under GSSoC'24 @Pratikdate 

Little about me : I am experienced contributor as I have completed _Hacktoberfest-2020_ and _Hactoberfest-2023_ successfully.

**Comment by Manikasethi** [comment]
Hey, Manika Sethi this side, I'm a GSSoC contributor and I am confident that I can address this issue effectively since I have understood the code. Could you please assign it to me? Thanks!

**Comment by prajapatihet** [comment]
Hey, Het this side, I'm a GSSoC contributor and I am confident that I can address this issue effectively since I have understood the code. Could you please assign it to me? Thanks!

**Comment by heysagnik** [comment]
This is not an issue
