### ISSUE TITLE
Improve layout by layout Builder

### ISSUE THREAD

**Issue by Pratikdate** [Pratikdate/ecard#3]
**Describe the bug**
App design not look responsive ,so by insert layout builder 

**To Reproduce**
1. As i created for home screen, create new folder for each nav screen in LayoutScreen directory
2. Go nav page ui
3. For each separate component widget , create class stateful/ stateless
4. Try to make UI responsive for each device by screen utils package,

**Expected behavior**
clear code and responsive page

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Phone

**Comment by vivekbargude** [comment]
Improve App Design Responsiveness Using LayoutBuilder

Description:
The current app design lacks responsiveness, impacting user experience. Propose implementing LayoutBuilder for effective adaptation to different screen sizes and orientations, enhancing usability across devices. Optimized and structured code ensuring responsiveness across devices, with seamless adaptation to screen sizes and orientations for a user-friendly experience.

Request to Assign:
Could you please assign this issue to me? I'm eager to take on the task and contribute to the project's success.

**Comment by Prathme07** [comment]
Please assign it to me. I will work on it.

**Comment by anuragJoshi05** [comment]
I also want to contribute to it, please assign it me as well..
