### ISSUE TITLE
App not redirecting to HomeScreen after reopening the application after login.

### ISSUE THREAD

**Issue by ShashankDeepak** [Pratikdate/ecard#4]
**Describe the bug**
After logging in when the app reopens, it redirects the user to the login page instead of the homepage. 

**To Reproduce**
1. Open the application
2. Login/Register
3. Close the application 
4. Reopen the application

**Expected behavior**
On reopening the application the user should be on the home screen.

**Comment by ShashankDeepak** [comment]
Please assign me the issue

**Comment by anuragJoshi05** [comment]
Please assign me the issue ,  I also want to contribute to this issue

**Comment by sheetal-ahuja** [comment]
hi could you tell me which version of flutter you are using as I am not able to run this project
