### ISSUE TITLE
Add a Logo to the App

### ISSUE THREAD

**Issue by AsmitaMishra24** [Pratikdate/ecard#42]
Is your feature request related to a problem? Please describe.
Without a distinctive logo, our app lacks a visual identity, making it less memorable and harder to distinguish from other apps. This can lead to a less engaging user experience and make the app appear less professional.

Describe the solution you'd like
I propose designing and adding a logo to the app. The logo should be visually appealing and reflect the app's core values and purpose. It should be displayed on the splash screen, main interface, and as the app icon. The design should be scalable to ensure it looks good on different devices and screen sizes.

Describe alternatives you've considered
Using a Standard Icon: We could use a standard or generic icon, but this would not provide a unique identity for our app and could look less professional.
Continuing Without a Logo: We could continue without a logo, but this would mean missing the opportunity to establish a stronger brand identity and improve user recognition and engagement.

**Comment by AsmitaMishra24** [comment]
Please assign me this issue under GSSOC'24

**Comment by Cheshta2203** [comment]
Can you assign me this issue @Pratikdate

**Comment by harsh6045** [comment]
Please assign me this issue under GSSOC'24 @Pratikdate

**Comment by prajapatihet** [comment]
Is this issues solved ? if not then assign to me @Pratikdate

**Comment by AsmitaMishra24** [comment]
I will complete it by tomorrow morning. Please do not reassign.

**Comment by hemjhakaul** [comment]
is this issue resolved? if not, i am up for it. @Pratikdate

**Comment by isha2125** [comment]
Is this issue is closed ?
If not can you kindly assign this to me ? @Pratikdate 
Thank you.

**Comment by aikansh008** [comment]
please assign this issue to me
