### ISSUE TITLE
Make analysis screen responsive

### ISSUE THREAD

**Issue by Pratikdate** [Pratikdate/ecard#8]
**Describe the bug**
By insert LayoutBuilder make analysis_screen responsive .

**To Produce**
Steps to proceed the change:
1. Create directory in AnalyticPageLayout
2. Inside directory create different files for layout
3. In analysis_screen page insert LayoutBuilder
4. make responsive for all mobile device.

**Expected behavior**
At outcome i expected clear code UI with responsive  page. 

**Smartphone (please complete the following information):**
 - Phone android 

**Additional context**
for reference you should check homepage layout.

**Comment by hariram4862** [comment]
can u please assign me this issue ?? i would like to contribute..

**Comment by VedaVarxha** [comment]
@Pratikdate I am well-versed in Flutter and would like to work on this issue under GSSOC'24. Please assign it to me

**Comment by hariram4862** [comment]
@Pratikdate can u pls add the labels ?

**Comment by Pratikdate** [comment]
For reference you should check Homepage layout

**Comment by vamsikandula03** [comment]
Could you please asign this task to me . I would like to contribute on this issue

**Comment by shivam-sharma-2000** [comment]
I would like to contribute to this issue. Can you please assign this issue to me?

**Comment by hariram4862** [comment]
@Pratikdate how should i proceed with this error ??.. google-services.json file is not there...shall i add new google-services.json file??

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\GSSoC-24\ecard-GSSoC-24\android\app\src\debug\google-services.json
  D:\GSSoC-24\ecard-GSSoC-24\android\app\src\google-services.json
  D:\GSSoC-24\ecard-GSSoC-24\android\app\google-services.json


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 10s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by Pratikdate** [comment]
Create Firebase project for this platform and download google-service.json make sure you enable auth through google and email.

**Comment by hariram4862** [comment]
@Pratikdate  yeah.. that's the way to go ... can u add it as a issue?.. let me first do that.. and complete this...

**Comment by kamalexe** [comment]
Could you please asign this task to me . I would like to contribute on this issue
