### ISSUE TITLE
After logout bottom nav arrange in stack

### ISSUE THREAD

**Issue by Pratikdate** [Pratikdate/ecard#9]
**Describe the bug**
After logout, bottom nav not get to destroy and when we log in its build stack.

**To Reproduce**
1. Go to user profile page
2. Click on logout 
3. try to login

**Expected behavior**
as start 

**Screenshots**
![WhatsApp Image 2024-05-10 at 20 41 08_680bfeb0](https://github.com/Pratikdate/ecard/assets/91735895/f0e2c1db-9e03-4d32-8461-942512f32b35)

**Smartphone (please complete the following information):**
 - Device: phone

**Comment by hariram4862** [comment]
@Pratikdate I would like to contribute to this issue, can u pls assign me?

**Comment by Prathme07** [comment]
please asign it to me

**Comment by vamsikandula03** [comment]
Could you please asign this task to me . I would like to contribute on this issue

**Comment by shivam-sharma-2000** [comment]
Hi @Pratikdate, I am a GSSOC'24 Contributor. I would like to contribute to this issue. Can you please assign this issue to me?

**Comment by ShashankDeepak** [comment]
Please assign me this task
